### ISSUE TITLE
unable to use in go 1.14

### ISSUE THREAD

**Issue by RELAXccc** [goldeneggg/structil#21]
go: finding module for package github.com/goldeneggg/structil
go: found github.com/goldeneggg/structil in github.com/goldeneggg/structil v0.4.4
go: github.com/goldeneggg/structil@v0.4.4 requires
        github.com/spf13/viper@v1.7.0 requires
        github.com/bketelsen/crypt@v0.0.3-0.20200106085610-5cbc8cc4026c requires
        cloud.google.com/go/firestore@v1.1.0 requires
        golang.org/x/exp@v0.0.0-20191030013958-a1ab85dbe136 requires
        dmitri.shuralyov.com/gpu/mtl@v0.0.0-20190408044501-666a987793e9: unrecognized import path "dmitri.shuralyov.com/gpu/mtl": https fetch: Get "https://dmitri.shuralyov.com/gpu/mtl?go-get=1": dial tcp 172.93.50.41:443: i/o timeout

**Comment by goldeneggg** [comment]
I can't reproduce this problem.

> "dmitri.shuralyov.com/gpu/mtl": https fetch: Get "https://dmitri.shuralyov.com/gpu/mtl?go-get=1": dial tcp 172.93.50.41:443: i/o timeout

I'm guessing it's not a my problem, but a different one
